name: backend-github-actions
on: [push]
jobs:
  CI_Steps:
    runs_on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo ok
        name: Code Build
      - run: echo ok
        name: Code Test
      - run: echo ok
        name: Code Review
      - run: echo ok
        name: Release Software



