name: Release-Workflow
on:
  push:
    tags:
      - "*"
jobs:
  call-Release-reusable:
    uses: s-devops-i2/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-frontend
      npm_install: false
    secrets: inherit